// A javascript-enhanced crossword puzzle [c] Jesse Weisbeck, MIT/GPL 
(function($) {
	$(function() {
		// provide crossword entries in an array of objects like the following example
		// Position refers to the numerical order of an entry. Each position can have 
		// two entries: an across entry and a down entry
		var entryData = [
        {
          clue: "19 vertical confundida, iza mil",
          answer: "Maiz",
          position: 1,
          orientation: "across",
          startx: 2,
          starty: 1,
        },
        {
          clue: "19 vertical con número de quijada",
          answer: "Pimenton",
          position: 4,
          orientation: "across",
          startx: 7,
          starty: 1,
        },
        {
          clue: "Astado al norte se ríe de esa 16 horizontal",
          answer: "Toronja",
          position: 10,
          orientation: "across",
          startx: 1,
          starty: 3,
        },
        {
          clue: "Intente comerse mi diligencia",
          answer: "Tramite",
          position: 11,
          orientation: "across",
          startx: 9,
          starty: 3,
        },
        {
          clue: "Embutido hecho con condimento y bebidas fermentadas",
          answer: "Salchichas",
          position: 12,
          orientation: "across",
          startx: 1,
          starty: 5,
        },
        {
          clue: "En wiki tacha 16 horizontal",
          answer: "Kiwi",
          position: 13,
          orientation: "across",
          startx: 12,
          starty: 5,
        },
        {
          clue: "En maltrecho abad el sur es cosa ridícula",
          answer: "Absurda",
          position: 14,
          orientation: "across",
          startx: 1,
          starty: 7,
        },
        {
          clue: "Asa 16 horizontal",
          answer: "Mango",
          position: 15,
          orientation: "across",
          startx: 11,
          starty: 7,
        },
        {
          clue: "Crece en los árboles cabeza de foca en la vía",
          answer: "Fruta",
          position: 16,
          orientation: "across",
          startx: 1,
          starty: 9,
        },
        {
          clue: "Ácido contra Regina desquiciada",
          answer: "Vinagre",
          position: 19,
          orientation: "across",
          startx: 9,
          starty: 9,
        },
        {
          clue: "Borracho sale uno a río español",
          answer: "Ebro",
          position: 22,
          orientation: "across",
          startx: 1,
          starty: 11,
        },
        {
          clue: "Borracha, me revuelvo cuando la primera entra en cuadrilla",
          answer: "Embriagada",
          position: 23,
          orientation: "across",
          startx: 6,
          starty: 11,
        },
        {
          clue: "En continente hay mil puntos de olvido",
          answer: "Amnesia",
          position: 25,
          orientation: "across",
          startx: 1,
          starty: 13,
        },
        {
          clue: "¿Cantamos todos juntos? Arregla sí o un no!",
          answer: "Unisono",
          position: 26,
          orientation: "across",
          startx: 9,
          starty: 13,
        },
        {
          clue: "Prueba pelo esa española",
          answer: "Catalana",
          position: 27,
          orientation: "across",
          startx: 2,
          starty: 15,
        },
        {
          clue: "El destino es buscar sin comenzar",
          answer: "Azar",
          position: 28,
          orientation: "across",
          startx: 11,
          starty: 15,
        },
        {
          clue: "Desarmo literas para construir facistoles",
          answer: "Atriles",
          position: 2,
          orientation: "down",
          startx: 3,
          starty: 1,
        },
        {
          clue: "19 vertical para última mujer que está con uno en un lapso de tiempo",
          answer: "Zanahoria",
          position: 3,
          orientation: "down",
          startx: 5,
          starty: 1,
        },
        {
          clue: "Alisa lámina",
          answer: "Plancha",
          position: 4,
          orientation: "down",
          startx: 7,
          starty: 1,
        },
        {
          clue: "Con mil asalta los sentidos!",
          answer: "Matraca",
          position: 5,
          orientation: "down",
          startx: 9,
          starty: 1,
        },
        {
          clue: "Montón de paja fantástico sin la General Electric",
          answer: "Nial",
          position: 6,
          orientation: "down",
          startx: 11,
          starty: 1,
        },
        {
          clue: "Celebran que nada termina con abrazo de espías",
          answer: "Ofician",
          position: 7,
          orientation: "down",
          startx: 13,
          starty: 1,
        },
        {
          clue: "Encuentra escondido algo gratis? Barato!",
          answer: "Atisba",
          position: 8,
          orientation: "down",
          startx: 1,
          starty: 2,
        },
        {
          clue: "19 vertical del pequeño Pepe?",
          answer: "Pepino",
          position: 9,
          orientation: "down",
          startx: 15,
          starty: 2,
        },
        {
          clue: "Envía al río primera 16 horizontal",
          answer: "Mandarina",
          position: 15,
          orientation: "down",
          startx: 11,
          starty: 7,
        },
        {
          clue: "Taladros de 16 horizontales",
          answer: "Fresas",
          position: 16,
          orientation: "down",
          startx: 1,
          starty: 9,
        },
        {
          clue: "Interminable 6 sostiene a cura ebrio en país europeo",
          answer: "Ucrania",
          position: 17,
          orientation: "down",
          startx: 3,
          starty: 9,
        },
        {
          clue: "A mil protege con biombo",
          answer: "Mampara",
          position: 18,
          orientation: "down",
          startx: 7,
          starty: 9,
        },
        {
          clue: "Observar despiadada que sale de la tierra",
          answer: "Verdura",
          position: 19,
          orientation: "down",
          startx: 9,
          starty: 9,
        },
        {
          clue: "Estupenda onda? Mentira!",
          answer: "Guayola",
          position: 20,
          orientation: "down",
          startx: 13,
          starty: 9,
        },
        {
          clue: "Hernando está entre puntos pequeños",
          answer: "Enanos",
          position: 21,
          orientation: "down",
          startx: 15,
          starty: 9,
        },
        {
          clue: "Carta alta pa’ Cruz",
          answer: "Aspa",
          position: 24,
          orientation: "down",
          startx: 5,
          starty: 12,
        }
			];
	
		$('#puzzle-wrapper').crossword({
			entryData: entryData,
			showAnswers: false,
			id: "my-crossword",
			successCallback: function(){alert("Congratulations!");}
		});
		
	})
	
})(jQuery)
